name: ablm
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - pip
  - jupyter
  - ipykernel
  - bioconda::anarci
  - bioconda::abnumber
  - pip:
    - antiberty
    - ablang
    - ablang2
    - torch
    - "transformers==4.46.3"
    - umap-learn
    - matplotlib
    - seaborn
    - pandas
    - requests
    - tqdm
    - scikit-learn
    - numpy
    - olga
    - numba
    - xgboost
